version: '3'
services: 
    db:
        image: postgres
        volumes: 
            - postgres-data:/var/lib/postgresql/data
        environment: 
            - POSTGRES_HOST=db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
    api:
        build: .
        environment: 
            - POSTGRES_HOST=db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes:
            - .:/$WORKDIR
        ports:
            - $API_PORT:$CONTAINER_PORT
        depends_on:
            - db
        tty: true
        stdin_open: true
volumes:
    postgres-data:
        driver: local