default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch("POSTGRES_HOST") { db } %>
  username: <%= ENV.fetch("POSTGRES_USER") { postgres }%>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { postgres } %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production